State-of-the-Edge/lfedge-landscape

landscape.yml

Fix swapped URLs for Intel and ARM

Wrong URLs for Intel and ARM

---

settings.yml

Signed-off-by: Wes Reisz <wesley@section.io>

removed test for k8

---

landscape.yml
settings.yml

update to settings 

---

landscape.yml

Updating the description of cloudfront

Update Cloudfront description

---

settings.yml

Signed-off-by: Dan Kohn <dan@dankohn.com>

Hide license for .ORG category

---

landscape.yml
settings.yml

Added new category of membership

Liaison Category Added

---

landscape.yml

Adding VMWare NSX

---

landscape.yml

added StorageOS

---

landscape.yml

update Akraino stage

---

landscape.yml

add Graphcore to Accelerators

---

landscape.yml

add ASRock Rack to the yml
This will close issue "Add ASRock Rack to LF-Edge lanscape #90"

Add ASRock Rack

---

settings.yml

Replaced l.lfedge with landscape.edgedge

Replaced l.lfedge with landscape.edgedge

---

INSTALL.md
README.md
landscape.yml
package.json
processed_landscape.yml
settings.yml

Signed-off-by: Jordi Noguera <jordinoguera83+github@gmail.com>

Replace github.com/lf-edge with github.com/State-of-the-Edge

---

landscape.yml

Adding Cloudify.co as a edge orchestration platform to the state of the edge site.

Add Cloudify Edge Orchestration to landscape.yml

---

landscape.yml

Reverts State-of-the-Edge/lfedge-landscape#332

Revert "Add Cloudify Edge Orchestration to landscape.yml"

---

landscape.yml

update to member level

---

landscape.yml

Updated ThunderSoft name; closes #345

update ThunderSoft name

---

landscape.yml

Member updates

---

landscape.yml

Update Fledge project stage from At Large to Growth

update Fledge project stage

---

landscape.yml

update twitter handle

---

landscape.yml

add new member open-ix

---

landscape.yml

update member level

---

settings.yml

Swapping out SOTE banner with KubeCon ad that gives tribute to Dan Kohn.

swap out banner ad

---

landscape.yml

update OIF member entry

---

landscape.yml

Added under 'Other Edge Related Software' for immediate listing, while we consider making updates to add an 'Other' category under Platforms.

add Open Horizon to landscape

---

landscape.yml

may need to update to Spectrum, but leaving as is for now

add charter communications to wireline subcategory

---

landscape.yml

update members jan 2021

---

landscape.yml

remove redis

---

landscape.yml

remove cloudbrink mem

---

landscape.yml

remove member saic tesra

---

landscape.yml

remove tensor

---

landscape.yml

Updated stage of Open Horizon project from at large to growth.

updated Open Horizon to growth stage

---

landscape.yml

Already listed in General Members section, but was missing from the category listings.

added Foxconn to OEM category

---

landscape.yml

member update

---

landscape.yml

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

Move Nokia to General membership

---

.github/workflows/Update members.yml

*Please check each of these after submitting your pull request:*

Create Update members.yml

---

landscape.yml
missing.csv

Reverts State-of-the-Edge/lfedge-landscape#473

Revert "Update members"
